# Impact Analyzer: Scraping social media to measure demand {#pithy-slug}
<!-- slug should be shorthand -->
#### Keywords

finance, investing, social media, impact
<!-- add tech keywords -->
## A beginning.
<!-- use your headings! -->
Within the impact investing industry, there is an assertion from large financial institutions that there is not significant interest to build new investment products. The reason for their hypothesis is based in the asymmetric relationship most investors have with their financial advisors: they pay their advisors to know what to do with their money. The problem with this relationship is that many investors don't feel empowered to ask for what they want, particularly if the request is ill-defined as "impact investing" often is. Additionally, traditionally trained financial advisors often exhibit an initial reaction to tell their clients that impact investing is not a good move for their client's portfolio - because they're likely to lose money, or because there aren't enough options on the market, or simply because the advisor is bad at listening to his client's requests.
<!-- define impact investing, and pick a real client -->
The combination of these phenomenon results in an unheard demand reaching the level of financial institutions that can build the investment products. They aren't truly aware of what people would want to invest in, and so they're unwilling to take a huge risk to build something new without reasonable assurance that there would be a market for their product.
<!-- clear value proposition; are there estimates of the size of the untapped demand? -->
## A middle.

Enter Impact Analyzer. This crawling tool scrapes Facebook, LinkedIn and Twitter accounts to collect data on users that fit characteristics of our target demographic. Using LinkedIn, we could generate a database of possible investors who are employed, perhaps within specific geographic regions, and who we determine have some likelihood to invest using proxies such as estimated income. From here, we cross-reference this database with Facebook and Twitter in an effort to identify what social, environmental, or other issues are important to them. This could be based on organizations they like, news articles they share, people they follow, and other sources.
<!-- Is this a for profit service? You'll need to establish licensing agreements with the data providers, since crawling is likely a contract violation. If it is non-profit, you may have other options for acquiring the data. -->
For example, an individual who engages in a significant amount of internal travel content may be interested in investing in products that aid in international development. An individual with strong religious preferences may invest in products that align with the specific tenets of that religion. An individual who often reviews businesses on Yelp may be interested in investments in local small businesses in their area.
<!-- How will you establish these connections between social media use and investment opportunities? How hard is this problem? -->
From this analysis we would develop a list of top interests as well as an estimated market size for an impact-focused product. By aggregating these data an institutional firm could estimate the demand for a new investment product and would have already gathered a significantly sized initial demographic to target for sales and marketing.
<!-- clarify client -->
## An end.

There are a number of challenges this concept presents. Firstly, the product is only as good as the data that it is able to analyze. If a significant amount of people's personal information, likes and dislikes is protected behind inaccessible privacy setting, the output would no longer be entirely representative of the target demographic. Additionally, there is a significant number of parameters that need to be estimated, including algorithmically determining someone's likelihood to invest, as well as converting the aggregate of those profiles into a market size. It is unclear if financial institutions, the largest of whom are typically thought of as traditional and less innovative, really would be interested in using this type of information to inform their product building decisions. And even if they would be, there is not yet any indication of how valuable it would be to them.
