# Pet Wellness Sensor {#pet-healthcare}

#### Keywords

Healthcare, Sensors, Diabetes, Animals, Pets

## Managing pet health is hard

Data sicence is driving signficant strides human healthcare everyday, from better data collection that can be shared with a suite of healtchare professionals to on-body sensors that better predict upcoming health hazards. While these advances are spectacular and necessary, a different subset of our population has yet to reap the benefits in a significant way: our pets. 

I myself am a dog owner, and my dog Simba has lived with diabetes for the past two years. The challenges of caring for a diabetic dog are mostly in relation to her insulin dosage, and the stakes are high. I must be extremely precise with her feeding times and amounts so that I can administer the appropriate dosage of insulin, as perscribed by her doctor and adjusted every six months on average. Having her perscription amound adjusted requires her to be under doctor supervision for a 24 hour period during which she repeatedly has blood drawn every hour so that her blood glucose levels can be measured. This process is both traumatic and expensive, and most importantly, it does not capture what the variations in her health on a day-to-day basis. In fact, we have landed in the animal emergency room on more than one occassion because her insulin requirements had changed without me knowing.

## A solution exists

One promising solution to this problem comes from advancements in human diabetes treatment: an on-body sensor that can measure blood glucose levels without requiring that a blood sample be drawn^[FDA approves first blood sugar monitor without finger pricks. (2017). STAT. Retrieved 10 November 2017, from https://www.statnews.com/2017/09/28/blood-sugar-monitor-finger-pricks-diabetes/
]. The sensor is adhered to the upper arm and when a reading device makes contact with the sensor, it outputs current blood glucose levels as well as levels over the previous eight hour period. For a dog or cat, the sensor could be placed at the animal's neck while the reader is attached to the pet's collar. This would provide measurements of the animal's daily blood glucose levels that could be read after each meal and be used to inform how much insulin is required in that moment.

However, the technology need not stop there. By combining the blog glucose reader with an activity tracker, I can be sure that I am not only administering the correct amount of insulin based on real time data, but that I am also adjusting the amount of food my dog is given based on her caloric needs that day. Just like with humans, my dog would need to eat less on days when her activity levels are lower, and she would need to eat more on days when we visit the dog park and her activity is above average. By pairing this food recommendation with a real time blood glucose measure, I could be sure that Simba is getting the amount of food she needs and that her insulin is being administered based on that quantity, as well as any other internal factors that would shift her blood glucose level. This would ensure that I could manage her diabetes in the best way possible, using real time data that is reflective of her actual conditions each day.

## Beyond diabetes

The described product would greatly add to a pet owner's ability to manage its diabetes. However, the potential usefulness doesn't stop there.

Our ability to collect and analyze additional useful data on the pets in our lives could greatly add to our ability to care for them. While I have explored how this could change diabetes management, there would appear to be any number of additionally useful data points. According to a survey conducted by the Association for Pet Obesity Prevention, more than half of the dogs in this country can be classified as overweight or obese^[More than half of U.S. pets are overweight or obese, survey finds. (2017). Cbsnews.com. Retrieved 10 November 2017, from https://www.cbsnews.com/news/more-than-half-of-u-s-pets-are-overweight-or-obese-survey-finds/
]. Activity tracking that is paired with meal portion recommendations could help significantly reduce this number, increasing the health and overall life expectancy of these animals. Non invasive measures of detecting cancers and other life-threatening diseases are continually being immproved^[Pasinszki, T., Krebsz, M., Tung, T., & Losic, D. (2017). Carbon Nanomaterial Based Biosensors for Non-Invasive Detection of Cancer and Disease Biomarkers for Clinical Diagnosis. Sensors, 17(8), 1919. doi:10.3390/s17081919], and it is feasible that this type of technology may in the near future be useful for disease detection in animals as well.

Most pet owners want to do what's best for their animal family members, and for many, a lack of information prevents them from doing so. A pet wellness sensor would help pet owners understand what their pets can't tell them. The most prohibitive factor to wide spread adoption would of course be cost, but further technological developments promise to drive costs down, and there will always be a segment of the market who will go above and beyond to keep their pets healthy and happy.